CREATE TABLE CART
(
    ID            NUMBER PRIMARY KEY,
    STATUS        VARCHAR(255) NOT NULL,
    TOTAL_VALUE   NUMBER NOT NULL
);

CREATE SEQUENCE CART_SEQ INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE PRODUCT
(
    ID   VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRICE NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    DISCOUNT NUMBER,
    CART_ID NUMBER NOT NULL
);
